# Use an official Python runtime as a parent image
FROM python:3.10-slim

# Set environment variables
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

# Set the working directory in the container
WORKDIR /app

# Copy the requirements file into the container
COPY requirements.txt .

# Install dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Copy the entire project into the container
COPY . .

# Expose the port on which the app runs
EXPOSE 3000

# Run collectstatic (if using static files) and migrations
RUN python manage.py collectstatic --noinput
RUN python manage.py migrate



# Start the application with Gunicorn
CMD ["gunicorn", "--bind", "0.0.0.0:3000", "verfication.wsgi:application"]


